# Copyright 2022 HUNT Cloud
# See LICENSE file for licensing details.
#
# Learn more about config at: https://juju.is/docs/sdk/config

options:
  debug:
    default: false
    description: Debug mode (more logs)
    type: boolean
  verbosity:
    default: 0
    description: Ansible verbosity (0 - 6)
    type: int
  playbook:
    default: |
      - hosts: localhost
        connection: local
        become: true
        gather_facts: false
        tasks: []
    type: string
    description: |
      Ansible playbook file.
      Use yaml file with keys environment and hosts.
      Bundle example: 'include-file://files/playbook.yaml'
      Command example: 'juju config app_name playbook=@playbook.yaml'
  mount_path:
    default: ""
    type: string
    description: |
      If storage is added by Juju, charm will be bind mounted on this path.

      Default: /opt/charm-ansible/<app_name>/storage
  mount_mode:
    default: "0700"
    type: string
    description: |
      If storage is bind mounted charm will set directory mode.

      Default: 0700
  mount_owner:
    default: "root"
    type: string
    description: |
      If storage is bind mounted charm will set directory owner.

      Default: root
  mount_group:
    default: "root"
    type: string
    description: |
      If storage is bind mounted charm will set directory group.

      Default: root
  crontab:
    default: ""
    type: string
    description: |
      Crontab config for running regular tasks. Use multiple lines to add more cron jobs.
      Cron jobs will be placed in /etc/cron.d/charm_<app_name> config file.

      https://help.ubuntu.com/community/CronHowto#:~:text=Two%20Other%20Types%20of%20Crontab,-The%20crontab

      Formatting: '<minute> <hour> <day> <month> <weekday> <username> <script-with-parameters>'
      Example: '0 0 * * * root /usr/bin/true'

      Configure from example file: 'juju config $app_name playbook=@bundles/crontab.txt'
