# Copyright 2022 vagrant
# See LICENSE file for licensing details.
#
# TEMPLATE-TODO: change this example to suit your needs.
# If you don't need a config, you can remove the file entirely.
# It ties in to the example _on_config_changed handler in src/charm.py
#
# Learn more about config at: https://juju.is/docs/sdk/config

options:
  playbook:
    default: "{}"
    type: string
    description: |
      Ansible playbook file.
      Use yaml file with keys environment and hosts.
      Bundle example: 'include-file://files/playbook.yaml'
      Command example: juju config appname playbook:=@file.yaml


